# Generated by Django 2.2.2 on 2019-07-16 00:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0003_auto_20190715_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_corto', models.CharField(default='', max_length=3, unique=True)),
                ('municipio', models.CharField(blank=True, max_length=30, unique=True)),
                ('usuario', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 7, 15, 19, 55, 51, 540962))),
                ('status', models.BooleanField(default=True)),
                ('estado', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='estado.Estado')),
            ],
        ),
    ]
