# Generated by Django 2.2.2 on 2019-07-01 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_corto', models.CharField(default='', max_length=3, unique=True)),
                ('pais', models.CharField(default='', max_length=30)),
                ('usuario', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 7, 1, 1, 22, 21, 44609))),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
