# Generated by Django 2.2.2 on 2019-07-01 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 3, 8, 10, 454578)),
        ),
    ]
