# Generated by Django 2.2.2 on 2019-07-01 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0002_auto_20190701_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 3, 39, 34, 742706)),
        ),
    ]
