# Generated by Django 2.2.2 on 2019-07-01 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0002_auto_20190701_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_corto', models.CharField(default='', max_length=3, unique=True)),
                ('usuario', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 7, 1, 3, 8, 10, 456573))),
                ('status', models.BooleanField(default=True)),
                ('estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pais.Pais', unique=True)),
            ],
        ),
    ]
