# Generated by Django 2.2.2 on 2019-07-01 08:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0003_auto_20190701_0339'),
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='pais.Pais'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 3, 39, 34, 746692)),
        ),
    ]
